### ISSUE TITLE
No Z-Movement via "Macro Stage"

### ISSUE THREAD

**Issue by microphysics** [microphysics/cockpit#1]
This used to work last year, before I updated the code to match the design-changes of the past months.
Now, the stage can be moved in X, Y and Z via python code, but the GUI only moves the stage in X and Y.
Trying to move the stage in Z results in:
...site-packages/cockpit/events.py", line 95, in publish
func(*args, **kwargs)
TypeError: onMotion() takes 2 positional arguments but 4 were given

**Comment by carandraug** [comment]
The change that's causing you issues is f5295b9de784a382919

Basically, the `deviceName` and the `position` arguments were not used so we removed them. You need to fix your calls to `onMotion`. Since this is coming from the events module, you're doing this indirectly by publishing `STAGE_MOVER` events.  Look for those and pass only the `axis` argument (see on that commit how that was done for the other stage devices).

**Comment by carandraug** [comment]
I see now that you have already fixed that. I'm not sure what the issue might be without more details. Don't you get more on the traceback?

Can you check what event is it being published that's causing this? Add some prints on `cockpit.events.Publisher.publish` and check what was the event and args that causing it to fail.

**Comment by microphysics** [comment]
I actually included the fix for f5295b9 after I posted the issue. As I have noticed today, this fix removed the error-message, but the stage still doesn't move (which is my excuse for not noticing that the error message disappeared).

The events and arguments that get published reveal that it's using the dummyMover instead of the smaractMover when moving the z-axis via Macro Stage.

**Comment by carandraug** [comment]
Ah! I see the problem now. `SmaractXYZ` device class is an XYZ stage but on its `getHandlers` method it only returns an handler for the X and Y axis. Because there's no Z axis, `DeviceDepot` injects a dummy Z axis so that users can at least try cockpit (cockpit requires motorized XYZ axis).

You need to `SmaractXYZ.getHandlers` to return a `PositionerHandler` for axis 2 (Z).

**Comment by microphysics** [comment]
Oh, looks like I messed that up when copy&pasting the new result.append-part from physikInstrumenteM687.py, thx!
